# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Ashita Dashottar'
tagline:             ''
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ashita Dashottar
  email:             ashitadashottar6@gmail.com
  email2:            'abc@xyz'
  github:            ashid6
  resume:            resume

# Custom vars
version:             1.0.0
