# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'TryCatch'
tagline:             ''
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shirsh Zibbu
  email:             zibbu.shirsh@gmail.com
  email2:            f2013450@pilani.bits-pilani.ac.in
  github:            zhirzh
  resume:            resume

# Custom vars
version:             1.0.0
